blank_issues_enabled: false
contact_links:
  - name: ğŸ’¬ GitHub Discussions
    url: https://github.com/naatin777/demmithub/discussions
    about: Please ask questions or discuss ideas here instead of opening an issue.
